# Generated by Django 5.2.1 on 2025-06-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_parser', '0002_alter_image_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
