services:
 parse_them_all:
  build:
   context: .
  image: parse_them_all:0.1
  volumes:
   - ./:/parse_them_all
  ports:
   - '8000:8000'
  command: 'python3 ./manage.py runserver 0.0.0.0:8000'
  depends_on:
   - database
   - rabbitmq

 worker1:
  build:
   context: .
  volumes:
   - ./:/parse_them_all
  command: 'celery -A parse_them_all worker -l INFO'
  depends_on:
   - database
   - rabbitmq

 database:
  image: postgres:17.5-alpine
  env_file:
    - .env
  volumes:
    - postgres_data:/var/lib/postgresql/data

 rabbitmq:
  image: rabbitmq:4.1.1

volumes:
 postgres_data:
