services:
 parse-them-all:
  build:
   context: ./parse_them_all
  volumes:
   - ./parse_them_all:/parse_them_all
  ports:
   - '8000:8000'
  networks:
   - parse_db_network
   - celery_network
  command: 'python3 ./manage.py runserver 0.0.0.0:8000'
  depends_on:
   - database
   - rabbitmq

 parse-worker:
  build:
   context: ./parse_them_all
  volumes:
   - ./parse_them_all:/parse_them_all
  networks:
   - parse_db_network
   - celery_network
  command: 'celery -A parse_them_all worker -Q parse_queue -l INFO'
  depends_on:
   - database
   - rabbitmq
 
 tesseract-api:
  build:
   context: ./tesseract_api
  command: 'python3 manage.py runserver 0.0.0.0:8001'
  volumes:
   - ./tesseract_api:/tesseract_api
  networks:
   - celery_network

 tesseract-worker:
  build:
   context: ./tesseract_api
  volumes:
   - ./tesseract_api:/tesseract_api
  networks:
   - celery_network
  command: 'celery -A tesseract_api worker -Q tessaract_queue -l INFO'
  depends_on:
   - rabbitmq

 database:
  image: postgres:17.5-alpine
  env_file:
    - ./parse_them_all/.env
  volumes:
    - postgres_data:/var/lib/postgresql/data
  networks:
   - parse_db_network

 rabbitmq:
  image: rabbitmq:4.1.1
  networks:
   - celery_network

volumes:
 postgres_data:

networks:
 parse_db_network:
 celery_network: 
