services:
 parse_them_all:
  build:
   context: .
  image: parse_them_all:0.1
  volumes:
   - ./:/parse_them_all
  ports:
   - '8000:8000'
  command: 'python3 ./manage.py runserver 0.0.0.0:8000'

 database:
  image: postgres:17.5-alpine
  environment:
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
 postgres_data:
