# Generated by Django 5.2.1 on 2025-06-17 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_object', models.ImageField(upload_to='')),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Processing'), (2, 'Success'), (3, 'Failed')], default=0)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
